### ISSUE TITLE
Source code to RGBAImage missing.  .process method not defined either in any blog posts

### ISSUE THREAD

**Issue by horseshoe7** [skyfe79/SwiftImageProcessing#6]
I was delighted to find this repo, but disappointed that you didn't include all the source for the RGBAImage stuff.  I pieced together most of what I need from the blog posts you provided, but nowhere did I find the implementation for the `.process` method.

**Comment by skyfe79** [comment]
@horseshoe7 Hi :)
You can find RGBAImage.process method on the playgrounds except for 01_MakeImageLibrary.playground. I'm sorry for the inconvenient.

https://github.com/skyfe79/SwiftImageProcessing/blob/4da1d2911844fe518e3e4b5baed8921db27580f0/10_Convolution.playground/Sources/RGBAImage.swift#L162
